// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: diskplan/v1/ipc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Stable rejection codes are part of the v1 compatibility contract.
public nonisolated enum Diskplan_V1_RejectCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case protocolMajorMismatch // = 1
  case missingRequiredCapability // = 2
  case businessBeforeHandshake // = 3
  case malformedEnvelope // = 4

  /// Reserved for transports that can safely report an oversized frame. The
  /// stdio transport treats oversize as fatal because the unread payload would
  /// leave the stream without a trustworthy frame boundary.
  case frameTooLarge // = 5
  case internalError // = 6
  case businessUnsupported // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .protocolMajorMismatch
    case 2: self = .missingRequiredCapability
    case 3: self = .businessBeforeHandshake
    case 4: self = .malformedEnvelope
    case 5: self = .frameTooLarge
    case 6: self = .internalError
    case 7: self = .businessUnsupported
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .protocolMajorMismatch: return 1
    case .missingRequiredCapability: return 2
    case .businessBeforeHandshake: return 3
    case .malformedEnvelope: return 4
    case .frameTooLarge: return 5
    case .internalError: return 6
    case .businessUnsupported: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Diskplan_V1_RejectCode] = [
    .unspecified,
    .protocolMajorMismatch,
    .missingRequiredCapability,
    .businessBeforeHandshake,
    .malformedEnvelope,
    .frameTooLarge,
    .internalError,
    .businessUnsupported,
  ]

}

public nonisolated struct Diskplan_V1_ProtocolVersion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var major: UInt32 = 0

  public var minor: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Diskplan_V1_Hello: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: Diskplan_V1_ProtocolVersion {
    get {_version ?? Diskplan_V1_ProtocolVersion()}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  public var hasVersion: Bool {self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  public mutating func clearVersion() {self._version = nil}

  public var requiredCapabilities: [String] = []

  public var optionalCapabilities: [String] = []

  public var implementation: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _version: Diskplan_V1_ProtocolVersion? = nil
}

public nonisolated struct Diskplan_V1_HelloAccepted: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var selectedVersion: Diskplan_V1_ProtocolVersion {
    get {_selectedVersion ?? Diskplan_V1_ProtocolVersion()}
    set {_selectedVersion = newValue}
  }
  /// Returns true if `selectedVersion` has been explicitly set.
  public var hasSelectedVersion: Bool {self._selectedVersion != nil}
  /// Clears the value of `selectedVersion`. Subsequent reads from it will return its default value.
  public mutating func clearSelectedVersion() {self._selectedVersion = nil}

  public var negotiatedCapabilities: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _selectedVersion: Diskplan_V1_ProtocolVersion? = nil
}

public nonisolated struct Diskplan_V1_HelloRejected: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var code: Diskplan_V1_RejectCode = .unspecified

  public var detail: String = String()

  public var peerVersion: Diskplan_V1_ProtocolVersion {
    get {_peerVersion ?? Diskplan_V1_ProtocolVersion()}
    set {_peerVersion = newValue}
  }
  /// Returns true if `peerVersion` has been explicitly set.
  public var hasPeerVersion: Bool {self._peerVersion != nil}
  /// Clears the value of `peerVersion`. Subsequent reads from it will return its default value.
  public mutating func clearPeerVersion() {self._peerVersion = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _peerVersion: Diskplan_V1_ProtocolVersion? = nil
}

public nonisolated struct Diskplan_V1_BusinessEnvelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: String = String()

  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Diskplan_V1_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sequence: UInt64 = 0

  public var body: Diskplan_V1_Envelope.OneOf_Body? = nil

  public var hello: Diskplan_V1_Hello {
    get {
      if case .hello(let v)? = body {return v}
      return Diskplan_V1_Hello()
    }
    set {body = .hello(newValue)}
  }

  public var helloAccepted: Diskplan_V1_HelloAccepted {
    get {
      if case .helloAccepted(let v)? = body {return v}
      return Diskplan_V1_HelloAccepted()
    }
    set {body = .helloAccepted(newValue)}
  }

  public var helloRejected: Diskplan_V1_HelloRejected {
    get {
      if case .helloRejected(let v)? = body {return v}
      return Diskplan_V1_HelloRejected()
    }
    set {body = .helloRejected(newValue)}
  }

  public var business: Diskplan_V1_BusinessEnvelope {
    get {
      if case .business(let v)? = body {return v}
      return Diskplan_V1_BusinessEnvelope()
    }
    set {body = .business(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public nonisolated enum OneOf_Body: Equatable, Sendable {
    case hello(Diskplan_V1_Hello)
    case helloAccepted(Diskplan_V1_HelloAccepted)
    case helloRejected(Diskplan_V1_HelloRejected)
    case business(Diskplan_V1_BusinessEnvelope)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "diskplan.v1"

nonisolated extension Diskplan_V1_RejectCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REJECT_CODE_UNSPECIFIED\0\u{1}REJECT_CODE_PROTOCOL_MAJOR_MISMATCH\0\u{1}REJECT_CODE_MISSING_REQUIRED_CAPABILITY\0\u{1}REJECT_CODE_BUSINESS_BEFORE_HANDSHAKE\0\u{1}REJECT_CODE_MALFORMED_ENVELOPE\0\u{1}REJECT_CODE_FRAME_TOO_LARGE\0\u{1}REJECT_CODE_INTERNAL_ERROR\0\u{1}REJECT_CODE_BUSINESS_UNSUPPORTED\0")
}

nonisolated extension Diskplan_V1_ProtocolVersion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProtocolVersion"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}major\0\u{1}minor\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.major) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.minor) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.major != 0 {
      try visitor.visitSingularUInt32Field(value: self.major, fieldNumber: 1)
    }
    if self.minor != 0 {
      try visitor.visitSingularUInt32Field(value: self.minor, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_ProtocolVersion, rhs: Diskplan_V1_ProtocolVersion) -> Bool {
    if lhs.major != rhs.major {return false}
    if lhs.minor != rhs.minor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Diskplan_V1_Hello: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hello"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{3}required_capabilities\0\u{3}optional_capabilities\0\u{1}implementation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._version) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.requiredCapabilities) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.optionalCapabilities) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.implementation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._version {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.requiredCapabilities.isEmpty {
      try visitor.visitRepeatedStringField(value: self.requiredCapabilities, fieldNumber: 2)
    }
    if !self.optionalCapabilities.isEmpty {
      try visitor.visitRepeatedStringField(value: self.optionalCapabilities, fieldNumber: 3)
    }
    if !self.implementation.isEmpty {
      try visitor.visitSingularStringField(value: self.implementation, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_Hello, rhs: Diskplan_V1_Hello) -> Bool {
    if lhs._version != rhs._version {return false}
    if lhs.requiredCapabilities != rhs.requiredCapabilities {return false}
    if lhs.optionalCapabilities != rhs.optionalCapabilities {return false}
    if lhs.implementation != rhs.implementation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Diskplan_V1_HelloAccepted: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HelloAccepted"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}selected_version\0\u{3}negotiated_capabilities\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._selectedVersion) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.negotiatedCapabilities) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._selectedVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.negotiatedCapabilities.isEmpty {
      try visitor.visitRepeatedStringField(value: self.negotiatedCapabilities, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_HelloAccepted, rhs: Diskplan_V1_HelloAccepted) -> Bool {
    if lhs._selectedVersion != rhs._selectedVersion {return false}
    if lhs.negotiatedCapabilities != rhs.negotiatedCapabilities {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Diskplan_V1_HelloRejected: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HelloRejected"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}detail\0\u{3}peer_version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.detail) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._peerVersion) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.code != .unspecified {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    if !self.detail.isEmpty {
      try visitor.visitSingularStringField(value: self.detail, fieldNumber: 2)
    }
    try { if let v = self._peerVersion {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_HelloRejected, rhs: Diskplan_V1_HelloRejected) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.detail != rhs.detail {return false}
    if lhs._peerVersion != rhs._peerVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Diskplan_V1_BusinessEnvelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BusinessEnvelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}payload\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_BusinessEnvelope, rhs: Diskplan_V1_BusinessEnvelope) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Diskplan_V1_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sequence\0\u{2}\u{9}hello\0\u{3}hello_accepted\0\u{3}hello_rejected\0\u{2}\u{8}business\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.sequence) }()
      case 10: try {
        var v: Diskplan_V1_Hello?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .hello(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .hello(v)
        }
      }()
      case 11: try {
        var v: Diskplan_V1_HelloAccepted?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .helloAccepted(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .helloAccepted(v)
        }
      }()
      case 12: try {
        var v: Diskplan_V1_HelloRejected?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .helloRejected(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .helloRejected(v)
        }
      }()
      case 20: try {
        var v: Diskplan_V1_BusinessEnvelope?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .business(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .business(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.sequence != 0 {
      try visitor.visitSingularUInt64Field(value: self.sequence, fieldNumber: 1)
    }
    switch self.body {
    case .hello?: try {
      guard case .hello(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .helloAccepted?: try {
      guard case .helloAccepted(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .helloRejected?: try {
      guard case .helloRejected(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .business?: try {
      guard case .business(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Diskplan_V1_Envelope, rhs: Diskplan_V1_Envelope) -> Bool {
    if lhs.sequence != rhs.sequence {return false}
    if lhs.body != rhs.body {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
