#!/usr/bin/env python3
"""Generate compile-time Swift byte arrays from canonical Rules source assets."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


MAX_ASSET_BYTES = 1_048_576
BYTES_PER_LINE = 16


def read_bounded(path: Path, maximum: int) -> bytes:
    with path.open("rb") as source:
        contents = source.read(maximum + 1)
    if len(contents) > maximum:
        raise ValueError("asset exceeds the 1 MiB source limit")
    return contents


def render_array(name: str, label: str, contents: bytes) -> str:
    rows = []
    for offset in range(0, len(contents), BYTES_PER_LINE):
        chunk = contents[offset : offset + BYTES_PER_LINE]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    body = "\n".join(rows)
    return f"  /// Exact canonical bytes from `{label}`.\n  public static let {name} = Data([\n{body}\n  ])\n"


def render(root: Path) -> bytes:
    built_in = read_bounded(root / "rules/builtin-v1.json", MAX_ASSET_BYTES)
    default_policy = read_bounded(
        root / "rules/user-policy-default-v1.json", MAX_ASSET_BYTES
    )
    source = (
        "// Generated by scripts/generate-rule-assets.py; do not edit.\n"
        "import Foundation\n\n"
        "/// Compile-time canonical Rules bytes; this type performs no filesystem access.\n"
        "public enum BundledRuleAssets {\n"
        + render_array("builtInRulesData", "rules/builtin-v1.json", built_in)
        + "\n"
        + render_array(
            "defaultPolicyData", "rules/user-policy-default-v1.json", default_policy
        )
        + "}\n"
    )
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the generated bytes with the checked-in Swift source",
    )
    arguments = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    output = root / "swift/Sources/DiskplanRules/BundledRuleAssets.generated.swift"
    try:
        expected = render(root)
        if arguments.check:
            actual = read_bounded(output, len(expected))
            if actual != expected:
                print("generated Rules asset source is stale", file=sys.stderr)
                return 1
            print("generated Rules asset source is current")
            return 0
        output.write_bytes(expected)
        print("generated compile-time Rules asset source")
        return 0
    except (OSError, ValueError) as error:
        print(f"Rules asset generation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
