[package]
name = "diskplan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crossterm.workspace = true
diskplan-core = { path = "../diskplan-core" }
diskplan-proto = { path = "../diskplan-proto" }
futures-util.workspace = true
prost.workspace = true
ratatui.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile.workspace = true
